# Generated by Django 5.0.3 on 2024-11-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='uso',
            field=models.TextField(blank=True, help_text='Especifica el uso recomendado del producto', null=True, verbose_name='Uso del producto'),
        ),
    ]
